version: "3.9"
services:
  database:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: db_crud
    ports:
      - "3306:3306"  # Expose ke host
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
