"""nama_pesan

Revision ID: 65b6e70c95bb
Revises: 5b125b26f813
Create Date: 2025-05-12 18:29:51.595379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65b6e70c95bb'
down_revision: Union[str, None] = '5b125b26f813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_user_email'), 'tb_user', ['email'], unique=False)
    op.create_index(op.f('ix_tb_user_id'), 'tb_user', ['id'], unique=False)
    op.create_index(op.f('ix_tb_user_name'), 'tb_user', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_user_name'), table_name='tb_user')
    op.drop_index(op.f('ix_tb_user_id'), table_name='tb_user')
    op.drop_index(op.f('ix_tb_user_email'), table_name='tb_user')
    op.drop_table('tb_user')
    # ### end Alembic commands ###
